# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "docstring-parser" = super.buildPythonPackage rec {
    pname = "docstring-parser";
    version = "0.16";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/7c/e9fcff7623954d86bdc17782036cbf715ecab1bec4847c008557affe1ca8/docstring_parser-0.16-py3-none-any.whl";
      sha256 = "0dq6m7zswq1vdvi9dl42k5iyy6gj4k0pxvzd0b8r2djd6n3i62mz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "eval-type-backport" = super.buildPythonPackage rec {
    pname = "eval-type-backport";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/ac/aa3d8e0acbcd71140420bc752d7c9779cf3a2a3bb1d7ef30944e38b2cd39/eval_type_backport-0.2.0-py3-none-any.whl";
      sha256 = "0cwrkifh3qk74s8xfrpsvygy9dbbkmw9lwxqh05a7ia01p9p6bxc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "markdown-it-py" = super.buildPythonPackage rec {
    pname = "markdown-it-py";
    version = "3.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl";
      sha256 = "1cfam2hw2bfjiwxf9038yj3cqrcpiw7c9n6q5hirdgb0bj21clim";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."mdurl"
    ];
  };
  "mdurl" = super.buildPythonPackage rec {
    pname = "mdurl";
    version = "0.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl";
      sha256 = "1y5qjqhmq2nm7xj6w5rrp503r7jhj7zr2qcnr6gs858nwm0ql044";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pygments" = super.buildPythonPackage rec {
    pname = "pygments";
    version = "2.17.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/9c/372fef8377a6e340b1704768d20daaded98bf13282b5327beb2e2fe2c7ef/pygments-2.17.2-py3-none-any.whl";
      sha256 = "0v44mw2dskc0rmx6926qfm8r9s6561684m4my8ck43vxqhk2hz5j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "rich" = super.buildPythonPackage rec {
    pname = "rich";
    version = "13.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/67/a37f6214d0e9fe57f6ae54b2956d550ca8365857f42a1ce0392bb21d9410/rich-13.7.1-py3-none-any.whl";
      sha256 = "08kj1m6yc41ikr7cvgzljjm0ld9k1pq0pqz9ahplissr9wqsxnsf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."markdown-it-py"
      self."pygments"
    ];
  };
  "shtab" = super.buildPythonPackage rec {
    pname = "shtab";
    version = "1.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e2/d1/a1d3189e7873408b9dc396aef0d7926c198b0df2aa3ddb5b539d3e89a70f/shtab-1.7.1-py3-none-any.whl";
      sha256 = "10wr4lgaahadp9wv9iik3s4q6y2jfp46was9c9xcgm12j3zx5lrj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/f3/936e209267d6ef7510322191003885de524fc48d1b43269810cd589ceaf5/typing_extensions-4.11.0-py3-none-any.whl";
      sha256 = "0yiqq03194im2vnsakm10rli5n3rbf6mbdsvfz7g9nkyi5r4vyf1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tyro" = super.buildPythonPackage rec {
    pname = "tyro";
    version = "0.8.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/f6/0b3dca524fdba07dff7b1a029e5546212440e7d2ebd60fc5fc3f4c5d0fbc/tyro-0.8.3-py3-none-any.whl";
      sha256 = "19jismfq7z5glzsavi8wni4g2l1qhb2qd6v5y0gdpxg7fk4mgihi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docstring-parser"
      self."eval-type-backport"
      self."rich"
      self."shtab"
      self."typing-extensions"
    ];
  };
}
